### ISSUE TITLE
テストコードが走らない

### ISSUE THREAD

**Issue by hiroki802** [t-cool/cl-tutor#1]
I made a quiz and the test code, but the error occurs.

```lisp
; file: /Users/noguchihiroki/.roswell/local-projects/t-cool/cl-tutor/data/Chapter05/ex05.lisp
; in: :DEFUN :F5-1                                                      
;     (:DEFUN :F5-1 NIL)                                               
;                                                                      
; caught STYLE-WARNING:                                                 
;   undefined function: :DEFUN                                         
;                                                                      
; compilation unit finished                                            
;   Undefined function:                                                
;     :DEFUN                                                           
;   caught 1 STYLE-WARNING condition                                   
While evaluating the form starting at line 5, column 0                
 of #P"/Users/noguchihiroki/.roswell/local-projects/t-cool/cl-tutor/data/Chapter05/ex05.lisp":The function :DEFUN is undefined.
NIL
```

**Comment by asciian** [comment]
your comments should be wrapped code block in markdown. The syntax highlight makes issue more clearly. Thanks!

**Comment by asciian** [comment]
I cannot run your error because I know not what you says about the test. Please tell me how to run your error with the step by step. But It's seems that the reader (or parser?) makes the error because it reads`defun` in **keyword** packages.

**Comment by asciian** [comment]
Ah! Tests has two meanings. Is it means the answer of exercises? Then I'll tackle.

**Comment by hiroki802** [comment]
Hi, asciian. Thank you for your advice!
I meant the the answering code of exercises.
For example, in the case of Quiz 5-1, the quiz is as follws:

;; 問題 5-1
;;  ・消費税を計算して、次のように文字列で返す関数を定義してください。
;;  (f5-1 1000) 
;;   => "税抜価格は1,000円、税込価格は1,080円です。"
::
;;  ・関数名はf5-1、引数はpriceとしてください。

(defun f5-1()
  ;; codeをここに書いてください
)

And the test code (answering code) is as follows:
(prove:ok (equal (f5-1 1000) "税抜価格は1,000円、税込価格は1,080円です。"))

When the user push F5 button, all the test codes on the right buffer will be executed
at a time.

**Comment by hiroki802** [comment]
It was a typo...
On the fifth line, the ;; was typed as :: 
I fixed it, now I can check the answer as I expect.
