### ISSUE TITLE
Too complex for a new leaner

### ISSUE THREAD

**Issue by muyinliu** [t-cool/cl-tutor#2]
Thank you for bring this training system to the world. But cl-tutor is too complex to use for new leaners in follow reason:

- shortcut keys require a lot of time to fit in(except those people already use Emacs before)
- there are no "help" button or shortcut key that can lead to help doc

**Comment by t-cool** [comment]
Hi, muyinliu.
I agree on your opinion.  I'll add arrow keys to its key-bindings.  As for help information, I'll put it in the first chapter. Thanks!!!
