### ISSUE TITLE
Building cl-tutor and maintaining from January 1 to February 28.

### ISSUE THREAD

**Issue by t-coool** [t-cool/cl-tutor#3]
@cxxxr 

This is the issue(request) for you.
You built this system last month, and you fixed many issues after that.

We will use cl-tutor for this seminar:
https://tcool.connpass.com/event/75060

If you maintain this system during the seminar, T-cool will pay $150 for it.

I'd appreciate your help.

- T-cool

**Comment by cxxxr** [comment]
Of course!
I'll maintain cl-tutor during the seminar
Please free to contact me about cl-tutor!

**Comment by t-coool** [comment]
Thank you for accepting our offer.
I appreciate your help!
